#!/bin/bash
#
# pre-commit hook to help ensure that:
#   - translation catalogues are recompiled before commits to reduce diff size.
#

# If we are performing a commit in which some translation file changed ...
if [ -n "$( git diff --cached --name-only --diff-filter=ACM | grep "LC_MESSAGES/cdedb.po" )" ]; then

    # ...recompile the catalogue.
    echo "Detected changes in translations. Recompiling translation catalogues..."
    make i18n-refresh 1&> /dev/null
    git add i18n/*/LC_MESSAGES/cdedb.po
    echo "... done"

fi
