#!/bin/bash
#
# pre-commit hook to recompile translation catalogues after merging in order to reduce diff size
#

# If we are performing a merge commit...
if [ -f .git/MERGE_MSG ]; then

    # ... in which some translation file changed ...
    if [ -n "$( git diff --cached --name-only --diff-filter=ACM | grep "LC_MESSAGES/cdedb.po" )" ]; then

        # ...recompile the catalogue.
        echo "Detected change in translations after merge commit. Recompiling translation catalogues..." 
        make i18n-refresh 1&> /dev/null
        git add i18n/*/LC_MESSAGES/cdedb.po
        echo "... done"

    fi

fi
