#!/usr/bin/env python3

CDB_DATABASE_NAME = "cdb_test"
SERVER_NAME_TEMPLATE = "test_{}_server"
LDAP_UNIT_NAME = "ou=personas-test,dc=cde-ev,dc=de"
STORAGE_DIR = "/tmp/cdedb-store/"
FRONTEND_LOG = "/tmp/test-cdedb-frontend.log"
CORE_SOCKET = "/run/cdedb/test-coreserver.sock"
CORE_STATE_FILE = "/run/cdedb/test-coreserver.pid"
CORE_ACCESS_LOG = "/tmp/test-cdedb-access-core.log"
CORE_BACKEND_LOG = "/tmp/test-cdedb-backend-core.log"
SESSION_SOCKET = "/run/cdedb/test-sessionserver.sock"
SESSION_STATE_FILE = "/run/cdedb/test-sessionserver.pid"
SESSION_ACCESS_LOG = "/tmp/test-cdedb-access-session.log"
SESSION_BACKEND_LOG = "/tmp/test-cdedb-backend-session.log"
CDE_SOCKET = "/run/cdedb/test-cdeserver.sock"
CDE_STATE_FILE = "/run/cdedb/test-cdeserver.pid"
CDE_ACCESS_LOG = "/tmp/test-cdedb-access-cde.log"
CDE_BACKEND_LOG = "/tmp/test-cdedb-backend-cde.log"
EVENT_SOCKET = "/run/cdedb/test-eventserver.sock"
EVENT_STATE_FILE = "/run/cdedb/test-eventserver.pid"
EVENT_ACCESS_LOG = "/tmp/test-cdedb-access-event.log"
EVENT_BACKEND_LOG = "/tmp/test-cdedb-backend-event.log"
