FROM debian:buster-20200607

RUN echo 'slapd slapd/password1 password s1n2t3h4d5i6u7e8o9a0s1n2t3h4d5i6u7e8o9a0' | debconf-set-selections \
    && echo 'slapd slapd/password2 password s1n2t3h4d5i6u7e8o9a0s1n2t3h4d5i6u7e8o9a0' | debconf-set-selections \
    \
    && apt-get update && apt-get install --yes --no-install-recommends \
    slapd \
    ldap-utils \
    unixodbc \
    odbc-postgresql

COPY ./related/docker/ldap-entrypoint.sh ./related/auto-build/files/stage2/odbc.ini ./sql-ldap.ldif /app/

RUN mv /app/ldap-entrypoint.sh /ldap-entrypoint.sh \
    && mv /app/odbc.ini /etc/odbc.ini

# Set custom entrypoint to perform additional work on first run.
ENTRYPOINT ["/ldap-entrypoint.sh"]

# Start slapd in foreground/debug mode without debug messages (-d 0).
CMD ["slapd", "-d", "0"]
