FROM debian:bookworm-20240130

RUN apt-get update && apt-get install --yes --no-install-recommends \
    python3 \
    python3-pip \
    python3-psycopg \
    python3-psycopg-pool \
    \
    && rm -rf /var/lib/apt/lists/* \
    \
    && python3 -m pip --no-cache-dir install --break-system-packages \
    ldaptor==21.2.0 \
    subman==0.1.1 \
    Twisted==22.4.0

COPY ./related/docker/ldaptor-entrypoint.sh ./related/auto-build/files/stage3 /tmp/autobuild/

RUN install -D /tmp/autobuild/localconfig.py /etc/cdedb/config.py \
    && touch /etc/cdedb/public-secrets.py \
    && touch /CONTAINER \
    \
    && cp /tmp/autobuild/ldaptor-entrypoint.sh /ldaptor-entrypoint.sh \
    \
    && rm -rf /tmp/autobuild

# make config persistent
VOLUME /etc/cdedb

EXPOSE 636

# mount the code here
WORKDIR /cdedb2

ENV CDEDB_CONFIGPATH /etc/cdedb/config.py
ENTRYPOINT ["/ldaptor-entrypoint.sh"]
CMD ["python3", "-m", "cdedb.ldap.main"]
