FROM debian:bullseye-20210816

# copy the ldap files and the ldap entrypoint into the container
COPY ./ldap/ ./related/docker/ldap-entrypoint.sh /tmp/ldap/

# create the log directory and touch the CONTAINER file
RUN mkdir /var/log/cdedb \
    && touch /CONTAINER

# Prepare the slapd debconfig
RUN sed -i -r "s/SLAPD_ADMIN_PASSWORD/${SLAPD_ADMIN_PASSWORD:-secret}/" /tmp/ldap/slapd-debconf.txt \
    && sed -i -r "s/SLAPD_PASSWORD/${SLAPD_PASSWORD:-secret}/" /tmp/ldap/slapd-debconf.txt

# Install the ldap specific packages with our custom slapd config
RUN cat /tmp/ldap/slapd-debconf.txt | debconf-set-selections \
    \
    && apt-get update && apt-get install --yes --no-install-recommends \
    slapd \
    ldap-utils \
    unixodbc \
    odbc-postgresql

# prepare odbc.ini file to enable database connection for ldap
RUN sed -i -r "s/DATABASE_NAME/${DATABASE_NAME}/" /tmp/ldap/odbc.ini \
    && sed -i -r "s/SERVER_NAME/${SERVER_NAME}/" /tmp/ldap/odbc.ini \
    && sed -i -r "s/USER_PASSWORD/${USER_PASSWORD}/" /tmp/ldap/odbc.ini \
    && mv /tmp/ldap/odbc.ini /etc/odbc.ini

# Prepare the ldif files, which are applied during first startup
RUN sed -i -r "s/OLC_DB_HOST/${SERVER_NAME}/" /tmp/ldap/cdedb-ldap.ldif \
    && sed -i -r "s/OLC_DB_NAME/${DATABASE_NAME}/" /tmp/ldap/cdedb-ldap.ldif \
    && sed -i -r "s/OLC_ROOT_PASSWORD/${OLC_ROOT_PASSWORD:-secret}/" /tmp/ldap/cdedb-ldap.ldif

# Copy all relevant files into the /app directory and the ldap entrypoint in root
RUN mkdir /app \
    && cp /tmp/ldap/config-ldap.ldif /app/ \
    && cp /tmp/ldap/cdedb-ldap.ldif /app/ \
    \
    && mv /tmp/ldap/ldap-entrypoint.sh /ldap-entrypoint.sh

# Set custom entrypoint to perform additional work on first run.
ENTRYPOINT ["/ldap-entrypoint.sh"]

# Start slapd in foreground/debug mode without debug messages (-d 0).
CMD ["slapd", "-d", "0"]
