FROM postgres:12.3

RUN localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8

COPY cdedb/database/*.sql /opt/schema/
COPY related/docker/postgres-init.sh /docker-entrypoint-initdb.d/postgres-init.sh
