FROM debian:trixie-20251020

# python and utilities to install packages via pip
# - python package dependencies:
#   - building/running pyicu: g++ pkg-config python3-dev libicu-dev
#   - building/running graphviz: graphviz
#   - building/running python-magic: libmagic1
#   - building/running python-systemd: libsystemd-dev
RUN apt-get update && apt-get install --yes --no-install-recommends \
    python3 \
    python3-pip \
    \
    g++ \
    pkg-config \
    python3-dev \
    libicu-dev \
    \
    graphviz \
    \
    libmagic1 \
    \
    libsystemd-dev \
    libicu-dev \
    \
    && rm -rf /var/lib/apt/lists/*

RUN pip install "uv>=0.11.0" --break-system-packages

# copy project configuration for uv
COPY ./pyproject.toml /tmp/

# install packages
RUN uv pip install --group /tmp/pyproject.toml:ldap --system --break-system-packages

RUN uv pip install -r /tmp/pyproject.toml --system --break-system-packages

COPY ./related/docker/ldaptor-entrypoint.sh ./related/auto-build/files/stage3 /tmp/autobuild/

RUN install -D /tmp/autobuild/localconfig.py /etc/cdedb/config.py \
    && touch /etc/cdedb/public-secrets.py \
    && touch /CONTAINER \
    \
    && cp /tmp/autobuild/ldaptor-entrypoint.sh /ldaptor-entrypoint.sh \
    \
    && rm -rf /tmp/autobuild

# make config persistent
VOLUME /etc/cdedb

EXPOSE 636

# mount the code here
WORKDIR /cdedb2

ENV CDEDB_CONFIGPATH /etc/cdedb/config.py
ENTRYPOINT ["/ldaptor-entrypoint.sh"]
CMD ["python3", "-m", "cdedb.ldap.main"]
