FROM cdedb:latest

RUN apt-get update && apt-get install --yes --no-install-recommends \
    bash-completion \
    man \
    less \
    vim \
    nano \
    emacs

# The local repo is mounted from the host, thus setting it globally.
RUN sudo -u cdedb git config --global core.hooksPath .githooks
