FROM debian:bullseye-20210816

# TODO replace with mount from host, snakeoil or first-run script?
RUN apt-get update && apt-get install --yes --no-install-recommends openssl \
    && mkdir /etc/ssl/apache2 \
    && openssl req \
        -x509 \
        -newkey rsa:4096 \
        -out /etc/ssl/apache2/server.pem \
        -keyout /etc/ssl/apache2/server.key \
        -days 365 \
        -nodes \
        -subj "/C=DE/O=CdE e.V./CN=cdedb.local/emailAddress=cdedb@lists.cde-ev.de" \
    && apt-get purge --yes --autoremove openssl \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install --yes --no-install-recommends \
    sudo \
    make \
    gettext \
    git \
    \
    openssl \
    apache2 \
    python3 \
    libapache2-mod-wsgi-py3 \
    \
    postgresql-client \
    \
    texlive \
    texlive-latex-extra \
    texlive-lang-german \
    texlive-luatex \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install --yes --no-install-recommends \
    python3-psycopg2 \
    python3-dateutil \
    python3-babel \
    python3-icu \
    python3-jinja2 \
    python3-tz \
    python3-sphinx \
    python3-lxml \
    python3-pil \
    python3-webtest \
    python3-werkzeug \
    python3-ldap3 \
    python3-passlib \
    python3-bleach \
    python3-magic \
    python3-sphinx-rtd-theme \
    python3-zxcvbn \
    python3-markdown \
    python3-requests \
    python3-qrcode \
    python3-vobject \
    python3-graphviz \
    python3-phonenumbers \
    \
    python3-pip \
    python3-click \
    \
    flake8 \
    isort \
    pylint \
    python3-freezegun \
    wget \
    unzip \
    \
    && apt-get install --yes python3-coverage \
    \
    && rm -rf /var/lib/apt/lists/* \
    \
    && python3 -m pip --no-cache-dir install \
    mailmanclient==3.3.3 \
    schulze_condorcet==2.0.0 \
    \
    && python3 -m pip --no-cache-dir install \
    mypy==0.910 \
    types-werkzeug \
    types-pytz \
    types-jinja2 \
    types-python-dateutil \
    types-freezegun \
    types-bleach \
    types-Markdown \
    types-click

# get the configuration files from the autobuild
COPY ./related/docker/cdedb-entrypoint.sh ./related/auto-build/files/stage3 /tmp/autobuild/

RUN cp /tmp/autobuild/cdedb-entrypoint.sh /cdedb-entrypoint.sh \
    \
    # configure apache
    && a2enmod ssl wsgi headers \
    && a2dissite 000-default \
    && echo "" > /etc/apache2/ports.conf \
    && cp /tmp/autobuild/cdedb-site.conf /etc/apache2/sites-available \
    && a2ensite cdedb-site \
    && cp /tmp/autobuild/index.html /var/www/html/ \
    \
    # add the mailman basic-auth password
    && cp /tmp/autobuild/mailman-htpasswd /etc/cdedb-mailman-htpasswd \
    && chown www-data:www-data /etc/cdedb-mailman-htpasswd \
    && chmod 640 /etc/cdedb-mailman-htpasswd \
    \
    # this is the DEFAULT_CONFIGPATH from cdedb_setup. We do not make this configurable
    # here, since its a default. However, passing a different configfile is possible
    # via the environment variable CDEDB_CONFIGPATH.
    && install -D /tmp/autobuild/localconfig.py /etc/cdedb/config.py \
    \
    # create the default (empty) secrets config. Sadly, we can not use the setup module
    # to get the file path via "python3 -m cdedb_setup secrets-configpath", so we
    # hardcode the default path here.
    && touch /etc/cdedb/public-secrets.py \
    \
    # add symlink to /cdedb2/cdedb and /cdedb2/cdedb_setup directory so python can find it
    && ln -s /cdedb2/cdedb/ /usr/lib/python3/dist-packages/cdedb \
    && ln -s /cdedb2/cdedb_setup/ /usr/lib/python3/dist-packages/cdedb_setup \
    \
    && rm -rf /tmp/autobuild \
    \
    # create the cdedb user \
    useradd --no-create-home cdedb \
    && echo "%cdedb ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers \
    \
    # create the magic file to signal that we are inside a docker container
    && touch /CONTAINER

# make storage persistent
# the storage and log dirs are created during the first startup in the entrypoint.
VOLUME /var/lib/cdedb
# make config persistent
VOLUME /etc/cdedb

EXPOSE 443

# mount the code here
WORKDIR /cdedb2

STOPSIGNAL SIGWINCH
ENTRYPOINT ["/cdedb-entrypoint.sh"]
CMD ["sh", "-c", "APACHE_HTTPD='exec /usr/sbin/apache2' exec apachectl -DFOREGROUND"]
