kind: pipeline
type: docker
name: default

workspace:
  base: /cdedb2
  path: .

clone:
  disable: true

steps:
- name: clone
  image: docker:20.10-git
  commands:
  - git clone $DRONE_GIT_HTTP_URL .
  # make use of our custom po file merge driver
  - apk add --no-cache gettext
  - |
    echo '''[merge "pomerge"]
        name = Gettext merge driver
        driver = i18n/git-merge-po.sh %O %A %B
    ''' >> ./.git/config
  - git fetch origin $DRONE_TARGET_BRANCH
  - git checkout $DRONE_TARGET_BRANCH
  - git fetch origin $DRONE_COMMIT
  - git merge $DRONE_COMMIT || (git merge --abort && git checkout $DRONE_COMMIT)
- name: build images
  image: docker:20.10
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  depends_on:
  - clone
  commands:
  # we do not tag a version as this would create many images
  # which would not be cleared from docker cache
  - docker build --file related/docker/Dockerfile-postgres --tag cdepostgres .
  - docker build --file related/docker/Dockerfile-cdedb --tag cdedb .
- name: mypy
  image: cdedb
  pull: never # do not try to pull image from docker hub
  depends_on:
  - build images
  commands:
  - make mypy
- name: lint
  image: cdedb
  pull: never # do not try to pull image from docker hub
  depends_on:
  - build images
  commands:
  - make lint
- name: cdb # is used as the hostname for the container
  image: cdepostgres
  pull: never # do not try to pull image from docker hub
  detach: true # detach to keep running for the following steps
  environment:
    POSTGRES_PASSWORD: passwd
  volumes:
  - name: database
    path: /var/lib/postgresql/data
  depends_on:
  - build images
- name: evolution-trial
  image: cdedb
  pull: never
  depends_on:
    - cdb
  volumes:
    - name: tmp_dir
      path: /tmp
  commands:
    - sleep 5
    - make i18n-compile # needed for sample-data step.
    - make sample-data # perform basic setup.
    - make sql-test # create the necessary test database.
    - bin/evolution-trial.sh origin/$DRONE_TARGET_BRANCH $DRONE_COMMIT
- name: frontend tests a-d
  image: cdedb
  pull: never # do not try to pull image from docker hub
  depends_on:
  - evolution-trial
  when:
    status:
    - failure
    - success
  volumes:
  - name: tmp_dir
    path: /tmp
  commands:
  - bin/check.py --verbose --first # everything before event
- name: frontend tests e-z
  image: cdedb
  pull: never # do not try to pull image from docker hub
  depends_on:
  - evolution-trial
  when:
    status:
    - failure
    - success
  volumes:
  - name: tmp_dir
    path: /tmp
  commands:
  - sleep 15 # wait for make sample-data to finish
  - bin/check.py --verbose --second # event and following
- name: backend tests
  image: cdedb
  pull: never # do not try to pull image from docker hub
  depends_on:
  - evolution-trial
  when:
    status:
    - failure
    - success
  volumes:
  - name: tmp_dir
    path: /tmp
  commands:
  - sleep 15 # wait for make sample-data to finish
  - bin/check.py --verbose --third
- name: xss
  image: cdedb
  pull: never
  depends_on:
  - evolution-trial
  when:
    status:
    - failure
    - success
  volumes:
  - name: tmp_dir
    path: /tmp
  commands:
    - sleep 15 # wait for make sample-data in testsuite to finish
    - make xss-check
- name: check for merge conflicts
  image: docker:20.10-git
  pull: never # do not try to pull image from docker hub
  depends_on:
  - frontend tests a-d
  - frontend tests e-z
  - backend tests
  - xss
  when:
    status:
    - failure
    - success
  commands:
  # let the pipeline fail if merge caused conflicts
  - apk add --no-cache gettext
  - git checkout $DRONE_TARGET_BRANCH
  - git merge $DRONE_COMMIT

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: database
  temp:
    medium: memory
- name: tmp_dir
  temp: {}

trigger:
  branch:
  - master
  - stable
#  - ci/*
