# /etc/systemd/system/cde-ldap.service.d/50-dev-override.conf
# This override is dev only.
[Unit]
AssertPathExists=!/PRODUCTIONVM

[Service]
Environment=CDEDB_CONFIGPATH=/cdedb2/tests/config/test_ldap.py
PrivateTmp=false
