# Fail2Ban configuration file
#
# Author: CdE Datenbankteam
[Definition]
# Matches messages such as:
# CdEDB login failure from 1.2.3.4 for emilia@example.cde
journalmatch = _SYSTEMD_UNIT=cdedb-app.service LOGGER_NAME=cdedb.backend.core
failregex = CdEDB login failure from <HOST> for
ignoreregex =
