# Fail2Ban configuration file
#
# Author: CdE Datenbankteam
[Definition]
# Matches messages such as:
# Sent password reset mail to emilia@example.de for IP 1.2.3.4.
journalmatch = _SYSTEMD_UNIT=cdedb-app.service LOGGER=cdedb.frontend.core
failregex = Sent password reset mail to .* for IP <HOST>
ignoreregex =
