# Fail2Ban configuration file
#
# Author: CdE Datenbankteam
[Definition]
# Matches messages such as:
# Received invalid API token from 127.0.1.1.
journalmatch = _SYSTEMD_UNIT=cdedb-app.service LOGGER_NAME=cdedb.backend.session
failregex = Received invalid API token from <HOST>
ignoreregex =
