#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          pyro-nameserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Pyro Nameserver
# Description:       Pyro nameserver daemon which provides resolution for
#                    names of remote objects.
### END INIT INFO

# Author: CdE Datenbankteam <cdedb@lists.schuelerakademie.de>

DESC="Pyro Nameserver"

case "$1" in
  start)
	cd /cdedb2
	log_daemon_msg "Starting Pyro nameserver" || true
	if start-stop-daemon --start --chuid backend:backend --background --make-pidfile --pidfile /var/run/pyro-nameserver.pid --exec /cdedb2/related/auto-build/files/stage3/make-pyro-nameserver.sh; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping Pyro nameserver" || true
	if start-stop-daemon --stop --pidfile /var/run/pyro-nameserver.pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
esac

exit 0

