\connect :cdb_database_name cdb
INSERT INTO core.personas (id, username, password_hash, display_name, is_active, status, db_privileges, cloud_account) VALUES (1, 'anton@example.cde', '$6$rounds=60000$uvCUTc5OULJF/kT5$CNYWFoGXgEwhrZ0nXmbw0jlWvqi/S6TDc1KJdzZzekFANha68XkgFFsw92Me8a2cVcK3TwSxsRPb91TLHF/si/', 'Anton', True, 0, 1, True);
INSERT INTO cde.member_data (persona_id, family_name, given_names, title, name_supplement, gender, birthday, telephone, mobile, address_supplement, address, postal_code, location, country, notes, birth_name, address_supplement2, address2, postal_code2, location2, country2, weblink, specialisation, affiliation, timeline, interests, free_form, balance, decided_search) VALUES (1, 'Administrator', 'Anton Armin A.', '', '', 1, date '1991-03-30', '+49 (234) 98765', '', '', 'Auf der Düne 42', '03205', 'Musterstadt', '', '', NULL, '', 'Unter dem Hügel 23', '22335', 'Hintertupfingen', '', NULL, NULL, NULL, NULL, NULL, NULL, 17.5, True);
INSERT INTO core.personas (id, username, password_hash, display_name, is_active, status, db_privileges, cloud_account) VALUES (2, 'berta@example.cde', '$6$rounds=60000$uvCUTc5OULJF/kT5$CNYWFoGXgEwhrZ0nXmbw0jlWvqi/S6TDc1KJdzZzekFANha68XkgFFsw92Me8a2cVcK3TwSxsRPb91TLHF/si/', 'Bertå', True, 0, 0, True);
INSERT INTO cde.member_data (persona_id, family_name, given_names, title, name_supplement, gender, birthday, telephone, mobile, address_supplement, address, postal_code, location, country, notes, birth_name, address_supplement2, address2, postal_code2, location2, country2, weblink, specialisation, affiliation, timeline, interests, free_form, balance, decided_search) VALUES (2, 'Beispiel', 'Bertålotta', 'Dr.', 'MdB', 0, date '1981-02-11', '+49 (5432) 987654321', '0163/123456789', 'bei Spielmanns', 'Im Garten 77', '34576', 'Utopia', '', '', 'Gemeinser', '', 'Strange Road 9 3/4', '8XA 45-$', 'Foreign City', 'Far Away', 'https://www.bundestag.cde', 'Alles', 'Jedermann', 'Überall', 'Immer', 'Jede Menge Gefasel', 12.5, True);
INSERT INTO core.personas (id, username, password_hash, display_name, is_active, status, db_privileges, cloud_account) VALUES (3, 'charly@example.cde', '$6$rounds=60000$uvCUTc5OULJF/kT5$CNYWFoGXgEwhrZ0nXmbw0jlWvqi/S6TDc1KJdzZzekFANha68XkgFFsw92Me8a2cVcK3TwSxsRPb91TLHF/si/', 'Charly', True, 1, 0, True);
INSERT INTO cde.member_data (persona_id, family_name, given_names, title, name_supplement, gender, birthday, telephone, mobile, address_supplement, address, postal_code, location, country, notes, birth_name, address_supplement2, address2, postal_code2, location2, country2, weblink, specialisation, affiliation, timeline, interests, free_form, balance, decided_search) VALUES (3, 'Clown', 'Charly C.', '', '', 2, date '1984-05-13', '', '', NULL, 'Am Zelt 1', '2345', 'Zirkusstadt', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, True);
INSERT INTO core.personas (id, username, password_hash, display_name, is_active, status, db_privileges, cloud_account) VALUES (4, 'daniel@example.cde', '$6$rounds=60000$uvCUTc5OULJF/kT5$CNYWFoGXgEwhrZ0nXmbw0jlWvqi/S6TDc1KJdzZzekFANha68XkgFFsw92Me8a2cVcK3TwSxsRPb91TLHF/si/', 'Daniel', False, 2, 0, False);
INSERT INTO cde.member_data (persona_id, family_name, given_names, title, name_supplement, gender, birthday, telephone, mobile, address_supplement, address, postal_code, location, country, notes, birth_name, address_supplement2, address2, postal_code2, location2, country2, weblink, specialisation, affiliation, timeline, interests, free_form, balance, decided_search) VALUES (4, 'Dino', 'Daniel D.', '', '', 1, date '1963-02-19', '', '', NULL, 'Am Denkmal 91', '76543', 'Atlantis', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, False);
INSERT INTO core.personas (id, username, password_hash, display_name, is_active, status, db_privileges, cloud_account) VALUES (5, 'emilia@example.cde', '$6$rounds=60000$uvCUTc5OULJF/kT5$CNYWFoGXgEwhrZ0nXmbw0jlWvqi/S6TDc1KJdzZzekFANha68XkgFFsw92Me8a2cVcK3TwSxsRPb91TLHF/si/', 'Emilia', True, 20, 0, False);
INSERT INTO event.user_data (persona_id, family_name, given_names, title, name_supplement, gender, birthday, telephone, mobile, address_supplement, address, postal_code, location, country, notes) VALUES (5, 'Eventis', 'Emilia E.', '', '', 0, date '2012-06-02', '+49 (5432) 555666777', '', NULL, 'Hohle Gasse 13', '56767', 'Wolkenkuckuksheim', 'Deutschland', '');
INSERT INTO core.personas (id, username, password_hash, display_name, is_active, status, db_privileges, cloud_account) VALUES (6, 'ferdinand@example.cde', '$6$rounds=60000$uvCUTc5OULJF/kT5$CNYWFoGXgEwhrZ0nXmbw0jlWvqi/S6TDc1KJdzZzekFANha68XkgFFsw92Me8a2cVcK3TwSxsRPb91TLHF/si/', 'Ferdinand', True, 0, 254, True);
INSERT INTO cde.member_data (persona_id, family_name, given_names, title, name_supplement, gender, birthday, telephone, mobile, address_supplement, address, postal_code, location, country, notes, birth_name, address_supplement2, address2, postal_code2, location2, country2, weblink, specialisation, affiliation, timeline, interests, free_form, balance, decided_search) VALUES (6, 'Findus', 'Ferdinand F.', '', '', 1, date '1988-01-01', '', '', NULL, 'Am Rathaus 1', '64358', 'Burokratia', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 22.2, True);
INSERT INTO core.personas (id, username, password_hash, display_name, is_active, status, db_privileges, cloud_account) VALUES (7, 'garcia@example.cde', '$6$rounds=60000$uvCUTc5OULJF/kT5$CNYWFoGXgEwhrZ0nXmbw0jlWvqi/S6TDc1KJdzZzekFANha68XkgFFsw92Me8a2cVcK3TwSxsRPb91TLHF/si/', 'Garcia', True, 0, 0, True);
INSERT INTO cde.member_data (persona_id, family_name, given_names, title, name_supplement, gender, birthday, telephone, mobile, address_supplement, address, postal_code, location, country, notes, birth_name, address_supplement2, address2, postal_code2, location2, country2, weblink, specialisation, affiliation, timeline, interests, free_form, balance, decided_search) VALUES (7, 'Generalis', 'Garcia G.', '', '', 0, date '1978-12-12', '', '', NULL, 'Bei der Wüste 39', '8888', 'Weltstadt', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 3.3, True); -- will be Orga

