#!/usr/bin/env python3

"""Additional strings for i18n which do not occur literally.

Run this as a script to print an autogenerated python file where further i18n strings
can be extracted from.

Automatically collects all CdEIntEnum members, all ConstraintViolations and all country codes.
"""

import itertools

from cdedb.common.n_ import n_
from cdedb.uncommon.intenum import CdEIntEnum


def main() -> None:
    # ruff: noqa: PLC0415
    import cdedb.enums
    from cdedb.common.validation.data import COUNTRY_CODES
    from cdedb.models.event_constraint_violations import ConstraintViolation

    enum_strings = []
    for cls in CdEIntEnum.__subclasses__():
        if cls not in cdedb.enums.NON_TRANSLATED_ENUMS:
            for enum_member in cls:
                enum_strings.append(str(enum_member))

    abstract, nonabstract = ConstraintViolation._get_subclasses()
    for cls in abstract:
        abstract_, nonabstract_ = cls._get_subclasses()
        abstract.extend(abstract_)
        nonabstract.extend(nonabstract_)

    violation_strings = [cls.__name__ for cls in nonabstract]

    country_code_strings = [f"CountryCodes.{cc}" for cc in COUNTRY_CODES]

    print("from cdedb.common.n_ import n_\n\n")
    for msg in itertools.chain(
        enum_strings, violation_strings, OTHER_STRINGS, country_code_strings
    ):
        msg = msg.replace('"', '\\"')
        print(f'n_("{msg}")')


OTHER_STRINGS = (
    #
    # Query scopes
    #
    n_("QueryScope.registration"),
    n_("QueryScope.event_course"),
    n_("QueryScope.lodgement"),
    #
    # Query datatypes
    #
    n_("str"),
    n_("int"),
    n_("float"),
    n_("date"),
    n_("datetime"),
    n_("bool"),
    n_("id"),
    # Meta info fields:
    n_("Finanzvorstand_Name"),
    n_("Finanzvorstand_Vorname"),
    n_("Finanzvorstand_Ort"),
    n_("Finanzvorstand_Adresse_Einzeiler"),
    n_("Finanzvorstand_Adresse_Zeile2"),
    n_("Finanzvorstand_Adresse_Zeile3"),
    n_("Finanzvorstand_Adresse_Zeile4"),
    n_("Vorstand"),
    n_("membership_fee_account"),
    n_("lastschrift_account"),
    n_("banner_before_login"),
    n_("banner_after_login"),
    n_("banner_genesis"),
    n_("cde_misc"),
    n_("lockdown_web"),
    #
    # Validation errors
    #
    n_("day is out of range for month"),
    n_("[<class 'decimal.ConversionSyntax'>]"),
    # zxcvbn feedback
    n_('Use a few words, avoid common phrases.'),
    n_('No need for symbols, digits, or uppercase letters.'),
    n_('Add another word or two. Uncommon words are better.'),
    n_('Straight rows of keys are easy to guess.'),
    n_('Short keyboard patterns are easy to guess.'),
    n_('Use a longer keyboard pattern with more turns.'),
    n_('Repeats like "aaa" are easy to guess.'),
    n_('Repeats like "abcabcabc" are only slightly harder to guess than "abc".'),
    n_('Avoid repeated words and characters.'),
    n_('Sequences like "abc" or "6543" are easy to guess.'),
    n_('Avoid sequences.'),
    n_("Recent years are easy to guess."),
    n_('Avoid recent years.'),
    n_('Avoid years that are associated with you.'),
    n_('Avoid dates and years that are associated with you.'),
    n_('This is a top-10 common password.'),
    n_('This is a top-100 common password.'),
    n_('This is a very common password.'),
    n_('This is similar to a commonly used password.'),
    n_('A word by itself is easy to guess.'),
    n_('Names and surnames by themselves are easy to guess.'),
    n_('Common names and surnames are easy to guess.'),
    n_("Capitalization doesn't help very much."),
    n_("All-uppercase is almost as easy to guess as all-lowercase."),
    n_("Reversed words aren't much harder to guess."),
    n_('Predictable substitutions like "@" instead of "a" don\'t help very much.'),
    #
    # subman localization
    #
    n_("subman_managing_not-pending"),
    n_("subman_managing_is-subscribed"),
    n_("subman_managing_is-unsubscribed"),
    n_("subman_managing_is-subscription-overridden"),
    n_("subman_managing_is-unsubscription-overridden"),
    n_("subman_managing_is-pending"),
    n_("subman_managing_not-subscription-overridden"),
    n_("subman_managing_not-unsubscription-overridden"),
    n_("subman_self_is-subscribed"),
    n_("subman_self_is-unsubscribed"),
    n_("subman_self_is-unsubscription-overridden"),
    n_("subman_self_is-pending"),
    n_("subman_self_not-pending"),
    n_("subman_managing_not-subscribable"),
    n_("subman_self_not-self-subscribable"),
    n_("subman_self_not-requestable"),
    n_("subman_managing_no-unsubscribe-possible"),
    n_("subman_managing_not-privileged"),
    n_("subman_managing_no-cleanup-necessary"),
    #
    # schulze-condorcet localization
    #
    n_("A candidate contains a forbidden character."),
    n_("Superfluous candidate in vote string."),
    n_("Missing candidate in vote string."),
    n_("Every candidate must occur exactly once in each vote."),
    #
    # Default Strings
    #
    n_("Cancel"),
    n_("Save"),
)


if __name__ == "__main__":
    main()
