#!/usr/bin/env python3

"""Routing table for the WSGI-application. This will get pretty big so put
it here where it is out of the way.
"""

import werkzeug.routing
rule = werkzeug.routing.Rule
sub = werkzeug.routing.Submount

class FilenameConverter(werkzeug.routing.BaseConverter):
    """Handles filename inputs in URL path."""
    regex = '[a-zA-Z0-9][-a-zA-Z0-9._]*'

## shorthands, mainly to avoid missing the comma to make a tuple for POST
_GET = ("GET", "HEAD")
_POST = ("POST",)

#: Using a routing map allows to do lookups as well as the reverse process
#: of generating links to targets instead of hardcoding them.
CDEDB_PATHS = werkzeug.routing.Map((
    werkzeug.routing.EndpointPrefix('core/', (
        rule("/", methods=_GET,
             endpoint="index"),
        rule("/error", methods=_GET,
             endpoint="error"),
        sub('/core', (
            rule("/login", methods=_POST,
                 endpoint="login"),
            rule("/logout", methods=_POST,
                 endpoint="logout"),
            rule("/log", methods=_GET,
                 endpoint="view_log"),
            rule("/meta", methods=_GET,
                 endpoint="meta_info_form"),
            rule("/meta", methods=_POST,
                 endpoint="change_meta_info"),
            rule("/persona/adminshow", methods=_GET,
                 endpoint="admin_show_user"),
            rule("/changelog/list", methods=_GET,
                 endpoint="list_pending_changes"),
            rule("/changelog/view", methods=_GET,
                 endpoint="view_changelog_meta"),
            sub('/self', (
                rule("/show", methods=_GET,
                     endpoint="mydata"),
                rule("/change", methods=_GET,
                     endpoint="change_user_form"),
                rule("/change", methods=_POST,
                     endpoint="change_user"),
                rule("/password/change", methods=_GET,
                     endpoint="change_password_form"),
                rule("/password/change", methods=_POST,
                     endpoint="change_password"),)),
            sub('/self/username', (
                rule("/change", methods=_GET,
                     endpoint="change_username_form"),
                rule("/change/mail", methods=_GET,
                     endpoint="send_username_change_link"),
                rule("/change/confirm", methods=_GET,
                     endpoint="do_username_change_form"),
                rule("/change", methods=_POST,
                     endpoint="do_username_change"),)),
            sub('/password', (
                rule("/reset", methods=_GET,
                     endpoint="reset_password_form"),
                rule("/reset/mail", methods=_GET,
                     endpoint="send_password_reset_link"),
                rule("/reset/confirm", methods=_GET,
                     endpoint="do_password_reset_form"),
                rule("/reset", methods=_POST,
                     endpoint="do_password_reset"),)),
            sub('/search', (
                rule("/user", methods=_GET,
                     endpoint="user_search"),
                rule("/archiveduser", methods=_GET,
                     endpoint="archived_user_search"),)),
            sub('/persona/<int:persona_id>', (
                rule("/adminchange", methods=_GET,
                     endpoint="admin_change_user_form"),
                rule("/adminchange", methods=_POST,
                     endpoint="admin_change_user"),
                rule("/privileges", methods=_GET,
                     endpoint="change_privileges_form"),
                rule("/privileges", methods=_POST,
                     endpoint="change_privileges"),
                rule("/promote", methods=_GET,
                     endpoint="promote_user_form"),
                rule("/promote", methods=_POST,
                     endpoint="promote_user"),
                rule("/password/adminreset", methods=_POST,
                     endpoint="admin_password_reset"),
                rule("/username/adminchange", methods=_GET,
                     endpoint="admin_username_change_form"),
                rule("/username/adminchange", methods=_POST,
                     endpoint="admin_username_change"),
                rule("/changelog/inspect", methods=_GET,
                     endpoint="inspect_change"),
                rule("/changelog/resolve", methods=_POST,
                     endpoint="resolve_change"),
                rule("/show", methods=_GET,
                     endpoint="show_user"),
                rule("/history", methods=_GET,
                     endpoint="show_history"),
                rule("/activity/change", methods=_POST,
                     endpoint="toggle_activity"),)),
            sub('/genesis', (
                rule("/request", methods=_GET,
                     endpoint="genesis_request_form"),
                rule("/request", methods=_POST,
                     endpoint="genesis_request"),
                rule("/verify", methods=_GET,
                     endpoint="genesis_verify"),
                rule("/list", methods=_GET,
                     endpoint="genesis_list_cases"),)),
            sub('/genesis/<int:case_id>', (
                rule("/decide", methods=_POST,
                     endpoint="genesis_decide"),
                rule("/timeout", methods=_POST,
                     endpoint="genesis_timeout"),)),
        )),)),
    werkzeug.routing.EndpointPrefix('cde/', (
        sub('/cde', (
            rule("/", methods=_GET,
                 endpoint="index"),
            rule("/log", methods=_GET,
                 endpoint="view_cde_log"),
            rule("/foto/<filename:foto>", methods=_GET,
                 endpoint="get_foto"),
            rule("/user/create", methods=_GET,
                 endpoint="create_user_form"),
            rule("/user/create", methods=_POST,
                 endpoint="create_user"),
            rule("/admission", methods=_GET,
                 endpoint="batch_admission_form"),
            rule("/admission", methods=_POST,
                 endpoint="batch_admission"),
            sub('/self', (
                rule("/consent", methods=_GET,
                     endpoint="consent_decision_form"),
                rule("/consent", methods=_POST,
                     endpoint="consent_decision"),)),
            sub('/search', (
                rule("/member", methods=_GET,
                     endpoint="member_search"),
                rule("/user", methods=_GET,
                     endpoint="user_search"),)),
            rule("/i25p", methods=_GET,
                 endpoint="i25p_index"),
            rule("/lastschrift", methods=_GET,
                 endpoint="lastschrift_index"),
            rule("/lastschrift/subscription", methods=_GET,
                 endpoint="lastschrift_subscription_form"),
            rule("/lastschrift/transaction/generate", methods=_POST,
                 endpoint="lastschrift_generate_transactions"),
            sub('/lastschrift/<int:lastschrift_id>', (
                rule("/skip", methods=_POST,
                     endpoint="lastschrift_skip"),
                rule("/change", methods=_GET,
                     endpoint="lastschrift_change_form"),
                rule("/change", methods=_POST,
                     endpoint="lastschrift_change"),
                rule("/revoke", methods=_POST,
                     endpoint="lastschrift_revoke"),
                sub('/transaction/<int:transaction_id>', (
                    rule("/finalize", methods=_POST,
                         endpoint="lastschrift_finalize_transaction"),
                    rule("/receipt", methods=_GET,
                         endpoint="lastschrift_receipt"),
                    rule("/rollback", methods=_POST,
                         endpoint="lastschrift_rollback_transaction"),)),)),
            sub('/user/<int:persona_id>', (
                rule("/show", methods=_GET,
                     endpoint="show_user"),
                rule("/adminchange", methods=_GET,
                     endpoint="admin_change_user_form"),
                rule("/adminchange", methods=_POST,
                     endpoint="admin_change_user"),
                rule("/foto/change", methods=_GET,
                     endpoint="set_foto_form"),
                rule("/foto/change", methods=_POST,
                     endpoint="set_foto"),
                rule("/lastschrift", methods=_GET,
                     endpoint="lastschrift_show"),
                rule("/lastschrift/create", methods=_GET,
                     endpoint="lastschrift_create_form"),
                rule("/lastschrift/create", methods=_POST,
                     endpoint="lastschrift_create"),
                rule("/membership/change", methods=_GET,
                     endpoint="modify_membership_form"),
                rule("/membership/change", methods=_POST,
                     endpoint="modify_membership"),)),
            sub('/semester', (
                rule("/show", methods=_GET,
                     endpoint="show_semester"),
                rule("/bill", methods=_POST,
                     endpoint="semester_bill"),
                rule("/eject", methods=_POST,
                     endpoint="semester_eject"),
                rule("/balance", methods=_POST,
                     endpoint="semester_balance_update"),
                rule("/advance", methods=_POST,
                     endpoint="semester_advance"),)),
            sub('/expuls', (
                rule("/address", methods=_POST,
                     endpoint="expuls_addresscheck"),
                rule("/advance", methods=_POST,
                     endpoint="expuls_advance"),)),
        )),)),
    werkzeug.routing.EndpointPrefix('event/', (
        sub('/event', (
            rule("/", methods=_GET,
                 endpoint="index"),
            rule("/search/user", methods=_GET,
                 endpoint="user_search"),
            rule("/user/create", methods=_GET,
                 endpoint="create_user_form"),
            rule("/user/create", methods=_POST,
                 endpoint="create_user"),
            rule("/genesis/<int:case_id>", methods=_GET,
                 endpoint="genesis_form"),
            rule("/genesis/<int:case_id>", methods=_POST,
                 endpoint="genesis"),
            rule("/pastevent/list", methods=_GET,
                 endpoint="list_past_events"),
            rule("/pastevent/create", methods=_GET,
                 endpoint="create_past_event_form"),
            rule("/pastevent/create", methods=_POST,
                 endpoint="create_past_event"),
            rule("/pastevent/log", methods=_GET,
                 endpoint="view_past_log"),
            rule("/event/list", methods=_GET,
                 endpoint="list_db_events"),
            rule("/institution/list", methods=_GET,
                 endpoint="list_institutions"),
            rule("/institution/create", methods=_POST,
                 endpoint="create_institution"),
            rule("/event/create", methods=_GET,
                 endpoint="create_event_form"),
            rule("/event/create", methods=_POST,
                 endpoint="create_event"),
            rule("/event/log", methods=_GET,
                 endpoint="view_log"),
            sub('/user/<int:persona_id>', (
                rule("/show", methods=_GET,
                     endpoint="show_user"),
                rule("/adminchange", methods=_GET,
                     endpoint="admin_change_user_form"),
                rule("/adminchange", methods=_POST,
                     endpoint="admin_change_user"),)),
            sub('/pastevent/<int:pevent_id>', (
                rule("/show", methods=_GET,
                     endpoint="show_past_event"),
                rule("/change", methods=_GET,
                     endpoint="change_past_event_form"),
                rule("/change", methods=_POST,
                     endpoint="change_past_event"),
                rule("/pastcourse/create", methods=_GET,
                     endpoint="create_past_course_form"),
                rule("/pastcourse/create", methods=_POST,
                     endpoint="create_past_course"),
                rule("/participant/add", methods=_POST,
                     endpoint="add_participant"),
                rule("/participant/remove", methods=_POST,
                     endpoint="remove_participant"),
                sub('/pastcourse/<int:pcourse_id>', (
                    rule("/show", methods=_GET,
                         endpoint="show_past_course"),
                    rule("/change", methods=_GET,
                         endpoint="change_past_course_form"),
                    rule("/change", methods=_POST,
                         endpoint="change_past_course"),
                    rule("/delete", methods=_POST,
                         endpoint="delete_past_course"),)),)),
            sub('/institution/<int:institution_id>', (
                rule("/change", methods=_GET,
                     endpoint="change_institution_form"),
                rule("/change", methods=_POST,
                     endpoint="change_institution"),)),
            sub('/event/<int:event_id>', (
                rule("/show", methods=_GET,
                     endpoint="show_event"),
                rule("/log", methods=_GET,
                     endpoint="view_event_log"),
                rule("/change", methods=_GET,
                     endpoint="change_event_form"),
                rule("/change", methods=_POST,
                     endpoint="change_event"),
                rule("/minorform", methods=_GET,
                     endpoint="get_minor_form"),
                rule("/orga/add", methods=_POST,
                     endpoint="add_orga"),
                rule("/orga/remove", methods=_POST,
                     endpoint="remove_orga"),
                rule("/minorform/change", methods=_POST,
                     endpoint="change_minor_form"),
                rule("/part/summary", methods=_GET,
                     endpoint="part_summary_form"),
                rule("/part/summary", methods=_POST,
                     endpoint="part_summary"),
                rule("/course/list", methods=_GET,
                     endpoint="course_list"),
                rule("/course/stats", methods=_GET,
                     endpoint="course_stats"),
                rule("/course/create", methods=_GET,
                     endpoint="create_course_form"),
                rule("/course/create", methods=_POST,
                     endpoint="create_course"),
                rule("/stats", methods=_GET,
                     endpoint="stats"),
                rule("/course/choices", methods=_GET,
                     endpoint="course_choices_form"),
                rule("/course/choices", methods=_POST,
                     endpoint="course_choices"),
                rule("/lock", methods=_POST,
                     endpoint="lock_event"),
                rule("/unlock", methods=_POST,
                     endpoint="unlock_event"),
                rule("/register", methods=_GET,
                     endpoint="register_form"),
                rule("/register", methods=_POST,
                     endpoint="register"),
                rule("/questionnaire/summary", methods=_GET,
                     endpoint="questionnaire_summary_form"),
                rule("/questionnaire/summary", methods=_POST,
                     endpoint="questionnaire_summary"),
                rule("/questionnaire/reorder", methods=_GET,
                     endpoint="reorder_questionnaire_form"),
                rule("/questionnaire/reorder", methods=_POST,
                     endpoint="reorder_questionnaire"),
                rule("/registration/add", methods=_GET,
                     endpoint="add_registration_form"),
                rule("/registration/add", methods=_POST,
                     endpoint="add_registration"),
                rule("/lodgement/overview", methods=_GET,
                     endpoint="lodgements"),
                rule("/lodgement/create", methods=_GET,
                     endpoint="create_lodgement_form"),
                rule("/lodgement/create", methods=_POST,
                     endpoint="create_lodgement"),
                rule("/registration/query", methods=_GET,
                     endpoint="registration_query"),
                rule("/registration/action", methods=_POST,
                     endpoint="registration_action"),
                rule("/checkin", methods=_GET,
                     endpoint="checkin_form"),
                rule("/checkin", methods=_POST,
                     endpoint="checkin"),
                rule("/field/setselect", methods=_GET,
                     endpoint="field_set_select"),
                rule("/field/summary", methods=_GET,
                     endpoint="field_summary_form"),
                rule("/field/summary", methods=_POST,
                     endpoint="field_summary"),
                rule("/download", methods=_GET,
                     endpoint="downloads"),
                rule("/archive", methods=_POST,
                     endpoint="archive_event"),
                sub("/download", (
                    rule("/namtag", methods=_GET,
                         endpoint="download_nametags"),
                    rule("/coursepuzzle", methods=_GET,
                         endpoint="download_course_puzzle"),
                    rule("/lodgementpuzzle", methods=_GET,
                         endpoint="download_lodgement_puzzle"),
                    rule("/courselists", methods=_GET,
                         endpoint="download_course_lists"),
                    rule("/lodgementlists", methods=_GET,
                         endpoint="download_lodgement_lists"),
                    rule("/participantlist", methods=_GET,
                         endpoint="download_participant_list"),
                    rule("/expuls", methods=_GET,
                         endpoint="download_expuls"),
                    rule("/export", methods=_GET,
                         endpoint="download_export"),)),
                sub('/course/<int:course_id>', (
                    rule("/show", methods=_GET,
                         endpoint="show_course"),
                    rule("/change", methods=_GET,
                         endpoint="change_course_form"),
                    rule("/change", methods=_POST,
                         endpoint="change_course"),
                    rule("/manage", methods=_GET,
                         endpoint="manage_attendees_form"),
                    rule("/manage", methods=_POST,
                         endpoint="manage_attendees"),)),
                sub('/registration', (
                    rule("/status", methods=_GET,
                         endpoint="registration_status"),
                    rule("/amend", methods=_GET,
                         endpoint="amend_registration_form"),
                    rule("/amend", methods=_POST,
                         endpoint="amend_registration"),
                    rule("/questionnaire", methods=_GET,
                         endpoint="questionnaire_form"),
                    rule("/questionnaire", methods=_POST,
                         endpoint="questionnaire"),)),
                sub('/registration/<int:registration_id>', (
                    rule("/show", methods=_GET,
                         endpoint="show_registration"),
                    rule("/change", methods=_GET,
                         endpoint="change_registration_form"),
                    rule("/change", methods=_POST,
                         endpoint="change_registration"),)),
                sub('/lodgement/<int:lodgement_id>', (
                    rule("/change", methods=_GET,
                         endpoint="change_lodgement_form"),
                    rule("/change", methods=_POST,
                         endpoint="change_lodgement"),
                    rule("/delete", methods=_POST,
                         endpoint="delete_lodgement"),
                    rule("/manage", methods=_GET,
                         endpoint="manage_inhabitants_form"),
                    rule("/manage", methods=_POST,
                         endpoint="manage_inhabitants"),
                    rule("/show", methods=_GET,
                         endpoint="show_lodgement"),)),
                sub('/field/<int:field_id>', (
                    rule("/set", methods=_GET,
                         endpoint="field_set_form"),
                    rule("/set", methods=_POST,
                         endpoint="field_set"),)),)),
        )),)),
    werkzeug.routing.EndpointPrefix('assembly/', (
        sub('/assembly', (
            rule("/", methods=_GET,
                 endpoint="index"),
            rule("/search/user", methods=_GET,
                 endpoint="user_search"),
            rule("/user/create", methods=_GET,
                 endpoint="create_user_form"),
            rule("/user/create", methods=_POST,
                 endpoint="create_user"),
            rule("/assembly/create", methods=_GET,
                 endpoint="create_assembly_form"),
            rule("/assembly/create", methods=_POST,
                 endpoint="create_assembly"),
            rule("/log", methods=_GET,
                 endpoint="view_log"),
            rule("/attachment/add", methods=_GET,
                 endpoint="add_attachment_form"),
            rule("/attachment/add", methods=_POST,
                 endpoint="add_attachment"),
            sub('/user/<int:persona_id>', (
                rule("/show", methods=_GET,
                     endpoint="show_user"),
                rule("/adminchange", methods=_GET,
                     endpoint="admin_change_user_form"),
                rule("/adminchange", methods=_POST,
                     endpoint="admin_change_user"),)),
            sub('/assembly/<int:assembly_id>', (
                rule("/show", methods=_GET,
                     endpoint="show_assembly"),
                rule("/change", methods=_GET,
                     endpoint="change_assembly_form"),
                rule("/change", methods=_POST,
                     endpoint="change_assembly"),
                rule("/signup", methods=_POST,
                     endpoint="signup"),
                rule("/attendees", methods=_GET,
                     endpoint="list_attendees"),
                rule("/conclude", methods=_POST,
                     endpoint="conclude_assembly"),
                rule("/ballot/list", methods=_GET,
                     endpoint="list_ballots"),
                rule("/ballot/create", methods=_GET,
                     endpoint="create_ballot_form"),
                rule("/ballot/create", methods=_POST,
                     endpoint="create_ballot"),
                rule("/attachment/<int:attachment_id>/get", methods=_GET,
                     endpoint="get_attachment"),
                rule("/attachment/<int:attachment_id>/remove", methods=_POST,
                     endpoint="remove_attachment"),
                sub('/ballot/<int:ballot_id>', (
                    rule("/show", methods=_GET,
                         endpoint="show_ballot"),
                    rule("/change", methods=_GET,
                         endpoint="change_ballot_form"),
                    rule("/change", methods=_POST,
                         endpoint="change_ballot"),
                    rule("/delete", methods=_POST,
                         endpoint="delete_ballot"),
                    rule("/vote", methods=_POST,
                         endpoint="vote"),
                    rule("/result", methods=_GET,
                         endpoint="get_result"),
                    rule("/attachment/<int:attachment_id>/get", methods=_GET,
                         endpoint="get_attachment"),
                    rule("/attachment/<int:attachment_id>/remove",
                         methods=_POST, endpoint="remove_attachment"),
                    rule("/candidate/add", methods=_POST,
                         endpoint="add_candidate"),
                    rule("/candidate/<int:candidate_id>/remove", methods=_POST,
                         endpoint="remove_candidate"),)),)),
        )),)),
    werkzeug.routing.EndpointPrefix('ml/', (
        sub('/ml', (
            rule("/", methods=_GET,
                 endpoint="index"),
            rule("/search/user", methods=_GET,
                 endpoint="user_search"),
            rule("/user/create", methods=_GET,
                 endpoint="create_user_form"),
            rule("/user/create", methods=_POST,
                 endpoint="create_user"),
            rule("/genesis/<int:case_id>", methods=_GET,
                 endpoint="genesis_form"),
            rule("/genesis/<int:case_id>", methods=_POST,
                 endpoint="genesis"),
            rule("/mailinglist/list", methods=_GET,
                 endpoint="list_mailinglists"),
            rule("/mailinglist/create", methods=_GET,
                 endpoint="create_mailinglist_form"),
            rule("/mailinglist/create", methods=_POST,
                 endpoint="create_mailinglist"),
            rule("/log", methods=_GET,
                 endpoint="view_log"),
            sub('/user/<int:persona_id>', (
                rule("/show", methods=_GET,
                     endpoint="show_user"),
                rule("/adminchange", methods=_GET,
                     endpoint="admin_change_user_form"),
                rule("/adminchange", methods=_POST,
                     endpoint="admin_change_user"),)),
            sub('/mailinglist/<int:mailinglist_id>', (
                rule("/show", methods=_GET,
                     endpoint="show_mailinglist"),
                rule("/change", methods=_GET,
                     endpoint="change_mailinglist_form"),
                rule("/change", methods=_POST,
                     endpoint="change_mailinglist"),
                rule("/log", methods=_GET,
                     endpoint="view_ml_log"),
                rule("/management", methods=_GET,
                     endpoint="management"),
                rule("/moderator/add", methods=_POST,
                     endpoint="add_moderator"),
                rule("/moderator/remove", methods=_POST,
                     endpoint="remove_moderator"),
                rule("/whitelist/add", methods=_POST,
                     endpoint="add_whitelist"),
                rule("/whitelist/remove", methods=_POST,
                     endpoint="remove_whitelist"),
                rule("/requests/decide", methods=_POST,
                     endpoint="decide_request"),
                rule("/subscriptions/add", methods=_POST,
                     endpoint="add_subscriber"),
                rule("/subscriptions/remove", methods=_POST,
                     endpoint="remove_subscriber"),
                rule("/self", methods=_POST,
                     endpoint="subscribe_or_unsubscribe"),
                rule("/subaddress/change", methods=_POST,
                     endpoint="change_address"),
                rule("/subaddress/confirm", methods=_GET,
                     endpoint="do_address_change"),
                rule("/check", methods=_GET,
                     endpoint="check_states"),)),
        )),)),
    ), converters={'filename': FilenameConverter})
