#!/usr/bin/env python3

"""Routing table for the WSGI-application. This will get pretty big so put
it here where it is out of the way.
"""

import werkzeug.routing
rule = werkzeug.routing.Rule

class FilenameConverter(werkzeug.routing.BaseConverter):
    """Handles filename inputs in URL path."""
    regex = '[a-zA-Z0-9][-a-zA-Z0-9._]*'

## shorthands, mainly to avoid missing the comma to make a tuple for POST
_GET = ("GET", "HEAD")
_POST = ("POST",)

#: Using a routing map allows to do lookups as well as the reverse process
#: of generating links to targets instead of hardcoding them.
CDEDB_PATHS = werkzeug.routing.Map((
    werkzeug.routing.EndpointPrefix('core/', (
        rule("/", methods=_GET, endpoint="index"),
        rule("/error", methods=_GET, endpoint="error"),
        rule("/login", methods=_POST, endpoint="login"),
        rule("/logout", methods=_POST, endpoint="logout"),
        rule("/mydata", methods=_GET, endpoint="mydata"),
        rule("/changepassword", methods=_GET,
             endpoint="change_password_form"),
        rule("/changepassword", methods=_POST,
             endpoint="change_password"),
        rule("/resetpassword", methods=_GET,
             endpoint="reset_password_form"),
        rule("/resetpasswordmail", methods=_GET,
             endpoint="send_password_reset_link"),
        rule("/dopasswordreset", methods=_GET,
             endpoint="do_password_reset_form"),
        rule("/dopasswordreset", methods=_POST,
             endpoint="do_password_reset"),
        rule("/adminpasswordreset/<int:persona_id>", methods=_POST,
             endpoint="admin_password_reset"),
        rule("/changeusername", methods=_GET,
             endpoint="change_username_form"),
        rule("/changeusernamemail", methods=_GET,
             endpoint="send_username_change_link"),
        rule("/dousernamechange/<int:persona_id>", methods=_GET,
             endpoint="do_username_change_form"),
        rule("/dousernamechange/<int:persona_id>", methods=_POST,
             endpoint="do_username_change"),
        rule("/adminusernamechange/<int:persona_id>", methods=_GET,
             endpoint="admin_username_change_form"),
        rule("/adminusernamechange/<int:persona_id>", methods=_POST,
             endpoint="admin_username_change"),
        rule("/showuser/<int:persona_id>", methods=_GET,
             endpoint="show_user"),
        rule("/adminshowuser", methods=_GET,
             endpoint="admin_show_user"),
        rule("/toggleactivity/<int:persona_id>", methods=_POST,
             endpoint="toggle_activity"),
        rule("/adjustprivileges/<int:persona_id>", methods=_GET,
             endpoint="adjust_privileges_form"),
        rule("/adjustprivileges/<int:persona_id>", methods=_POST,
             endpoint="adjust_privileges"),
        rule("/genesisrequest", methods=_GET,
             endpoint="genesis_request_form"),
        rule("/genesisrequest", methods=_POST,
             endpoint="genesis_request"),
        rule("/genesisverify", methods=_GET,
             endpoint="genesis_verify"),
        rule("/genesislistcases", methods=_GET,
             endpoint="genesis_list_cases"),
        rule("/genesisdecide", methods=_POST,
             endpoint="genesis_decide"),
        rule("/genesistimeout", methods=_POST,
             endpoint="genesis_timeout"),
        )),
    werkzeug.routing.EndpointPrefix('cde/', (
        werkzeug.routing.Submount('/cde', (
            rule("/", methods=_GET, endpoint="index"),
            rule("/showuser/<int:persona_id>", methods=_GET,
                 endpoint="show_user"),
            rule("/changeuser/<int:persona_id>", methods=_GET,
                 endpoint="change_user_form"),
            rule("/changeuser/<int:persona_id>", methods=_POST,
                 endpoint="change_user"),
            rule("/adminchangeuser/<int:persona_id>", methods=_GET,
                 endpoint="admin_change_user_form"),
            rule("/adminchangeuser/<int:persona_id>", methods=_POST,
                 endpoint="admin_change_user"),
            rule("/listpendingchanges", methods=_GET,
                 endpoint="list_pending_changes"),
            rule("/inspectchange/<int:persona_id>", methods=_GET,
                 endpoint="inspect_change"),
            rule("/resolvechange/<int:persona_id>", methods=_POST,
                 endpoint="resolve_change"),
            rule("/foto/<filename:foto>", methods=_GET,
                 endpoint="get_foto"),
            rule("/setfoto/<int:persona_id>", methods=_GET,
                 endpoint="set_foto_form"),
            rule("/setfoto/<int:persona_id>", methods=_POST,
                 endpoint="set_foto"),
            rule("/consentdecision", methods=_GET,
                 endpoint="consent_decision_form"),
            rule("/consentdecision", methods=_POST,
                 endpoint="consent_decision"),
            rule("/membersearch", methods=_GET,
                 endpoint="member_search"),
            rule("/usersearchform", methods=_GET,
                 endpoint="user_search_form"),
            rule("/usersearch", methods=_GET,
                 endpoint="user_search"),
            rule("/archivedusersearchform", methods=_GET,
                 endpoint="archived_user_search_form"),
            rule("/archivedusersearch", methods=_GET,
                 endpoint="archived_user_search"),
            rule("/modifymembership/<int:persona_id>", methods=_GET,
                 endpoint="modify_membership_form"),
            rule("/modifymembership/<int:persona_id>", methods=_POST,
                 endpoint="modify_membership"),
            rule("/createuser", methods=_GET,
                 endpoint="create_user_form"),
            rule("/createuser", methods=_POST,
                 endpoint="create_user"),
            )),
        )),
    werkzeug.routing.EndpointPrefix('event/', (
        werkzeug.routing.Submount('/event', (
            rule("/", methods=_GET, endpoint="index"),
            rule("/showuser/<int:persona_id>", methods=_GET,
                 endpoint="show_user"),
            rule("/changeuser/<int:persona_id>", methods=_GET,
                 endpoint="change_user_form"),
            rule("/changeuser/<int:persona_id>", methods=_POST,
                 endpoint="change_user"),
            rule("/adminchangeuser/<int:persona_id>", methods=_GET,
                 endpoint="admin_change_user_form"),
            rule("/adminchangeuser/<int:persona_id>", methods=_POST,
                 endpoint="admin_change_user"),
            rule("/usersearchform", methods=_GET,
                 endpoint="user_search_form"),
            rule("/usersearch", methods=_GET,
                 endpoint="user_search"),
            rule("/createuser", methods=_GET,
                 endpoint="create_user_form"),
            rule("/createuser", methods=_POST,
                 endpoint="create_user"),
            rule("/genesis/<int:case_id>", methods=_GET,
                 endpoint="genesis_form"),
            rule("/genesis/<int:case_id>", methods=_POST,
                 endpoint="genesis"),
            rule("/listpastevents", methods=_GET,
                 endpoint="list_past_events"),
            rule("/showpastevent/<int:event_id>", methods=_GET,
                 endpoint="show_past_event"),
            rule("/changepastevent/<int:event_id>", methods=_GET,
                 endpoint="change_past_event_form"),
            rule("/changepastevent/<int:event_id>", methods=_POST,
                 endpoint="change_past_event"),
            rule("/createpastevent", methods=_GET,
                 endpoint="create_past_event_form"),
            rule("/createpastevent", methods=_POST,
                 endpoint="create_past_event"),
            rule("/showpastcourse/<int:event_id>/<int:course_id>",
                 methods=_GET, endpoint="show_past_course"),
            rule("/changepastcourse/<int:event_id>/<int:course_id>",
                 methods=_GET, endpoint="change_past_course_form"),
            rule("/changepastcourse/<int:event_id>/<int:course_id>",
                 methods=_POST, endpoint="change_past_course"),
            rule("/createpastcourse/<int:event_id>", methods=_GET,
                 endpoint="create_past_course_form"),
            rule("/createpastcourse/<int:event_id>", methods=_POST,
                 endpoint="create_past_course"),
            rule("/deletepastcourse/<int:event_id>/<int:course_id>",
                 methods=_POST, endpoint="delete_past_course"),
            rule("/addparticipant/<int:event_id>", methods=_POST,
                 endpoint="add_participant"),
            rule("/removeparticipant/<int:event_id>", methods=_POST,
                 endpoint="remove_participant"),
            rule("/listevents", methods=_GET,
                 endpoint="list_events"),
            rule("/showevent/<int:event_id>", methods=_GET,
                 endpoint="show_event"),
            rule("/changeevent/<int:event_id>", methods=_GET,
                 endpoint="change_event_form"),
            rule("/changeevent/<int:event_id>", methods=_POST,
                 endpoint="change_event"),
            rule("/getminorform/<int:event_id>", methods=_GET,
                 endpoint="get_minor_form"),
            rule("/addorga/<int:event_id>", methods=_POST,
                 endpoint="add_orga"),
            rule("/removeorga/<int:event_id>", methods=_POST,
                 endpoint="remove_orga"),
            rule("/changeminorform/<int:event_id>", methods=_POST,
                 endpoint="change_minor_form"),
            rule("/changepart/<int:event_id>/<int:part_id>",
                 methods=_GET, endpoint="change_part_form"),
            rule("/changepart/<int:event_id>/<int:part_id>", methods=_POST,
                 endpoint="change_part"),
            rule("/addpart/<int:event_id>", methods=_POST,
                 endpoint="add_part"),
            rule("/changefield/<int:event_id>/<int:field_id>",
                 methods=_GET, endpoint="change_field_form"),
            rule("/changefield/<int:event_id>/<int:field_id>", methods=_POST,
                 endpoint="change_field"),
            rule("/addfield/<int:event_id>", methods=_POST,
                 endpoint="add_field"),
            rule("/removefield/<int:event_id>", methods=_POST,
                 endpoint="remove_field"),
            rule("/createevent", methods=_GET,
                 endpoint="create_event_form"),
            rule("/createevent", methods=_POST,
                 endpoint="create_event"),
            rule("/showcourse/<int:event_id>/<int:course_id>", methods=_GET,
                 endpoint="show_course"),
            rule("/changecourse/<int:event_id>/<int:course_id>", methods=_GET,
                 endpoint="change_course_form"),
            rule("/changecourse/<int:event_id>/<int:course_id>", methods=_POST,
                 endpoint="change_course"),
            rule("/createcourse/<int:event_id>", methods=_GET,
                 endpoint="create_course_form"),
            rule("/createcourse/<int:event_id>", methods=_POST,
                 endpoint="create_course"),
            )),
        ))
    ), converters={'filename': FilenameConverter})
