#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          cdedb-rundir
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Create CdEDB dir in /run
# Description:       Create CdEDB dir in /run
### END INIT INFO

# Author: CdE Datenbankteam <cdedb@lists.schuelerakademie.de>

DESC="Create CdEDB dir in /run"

case "$1" in
  start)
        log_daemon_msg "Creating /run/cdedb" || true
	mkdir -p /run/cdedb
	chown backend:cdedb /run/cdedb
	chmod 775 /run/cdedb
        log_end_msg 0
	;;
  stop)
        log_daemon_msg "Deleting /run/cdedb" || true
	rm -rf /run/cdedb
        log_end_msg 0
	;;
esac

exit 0
