#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          runit
# Required-Start:    $remote_fs $syslog cdedb-rundir pyro-nameserver
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Runit
# Description:       Runit
### END INIT INFO

# Author: CdE Datenbankteam <cdedb@lists.schuelerakademie.de>

DESC="Runit"

case "$1" in
  start)
	cd /cdedb2
	log_daemon_msg "Starting Runit" || true
	if start-stop-daemon --start --background --make-pidfile --pidfile /var/run/runit.pid --exec /usr/sbin/runsvdir-start; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping Runit" || true
	if start-stop-daemon --stop --pidfile /var/run/runit.pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
esac

exit 0

